spring:
  application:
    name: hogwarts-artifacts-api
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
    driver-class-name: org.h2.Driver

# custom properties - to access example @Value("${api.endpoint.base-url}")
api:
  endpoint:
    base-url: /api/v1
